name: Download Artifact

on:
  workflow_dispatch:

jobs:
  print-artifact:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: hello
          path: hello.txt
      - name: cat Hello World file
        run: |
          cat hello.txt
